# Generated by Django 5.2 on 2025-05-08 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcampManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=255, unique=True)),
                ('mac_adr', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('A', 'Available'), ('O', 'Occupied'), ('M', 'Maintenance')], default='Available', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('pc_model', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'computer',
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bootcampManagement.computer', to_field='host_name'),
        ),
    ]
